### PR TITLE
Weekend Wariors -- May 4th-5th, 2019

### PR DESCRIPTION
**Pull request by nickcannariato**
# Description

@ajb85 and I have a free day on Sunday, May 5th, so we've decided we're going to spend some time cleaning up, refactoring, reorganizing, and otherwise documenting the backend code.

This is a tracking PR that will allow us to coordinate work and discuss what we want to accomplish before we get to the weekend. Work will be made in individual PRs which will then me merged into this one, and on Monday morning this PR will be available for review and merging.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## Change status
- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [x] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

**EDIT THIS WHEN TESTS ARE ADDED**

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by nickcannariato** [comment]
Things on my initial wishlist:

- [ ] Clean up the project structure
- [ ] Pull out middleware and helper functions where we see them
- [ ] Standardize the naming conventions
- [ ] Add Jest and Supertest as dev dependencies and write at least a _few_ tests
- [ ] Write documentation
    - [ ] "Getting Started" documentation to help future devs set up and deploy the application
    - [ ] "Database" documentation to explain the data model (including @DaftBeowulf's great DB diagram)
    - [ ] "Deployment" documentation to help with deploying the app and also documenting our infrastructure.
    - [ ] "Style Guide" documentation to explain the way the codde is written (why we use a particular casing or using `router.route()` and nested routes instead of `router.get()`, etc.)
- [ ] Convert the application to run on PM2 or some other production task runner instead of just running `node index.js` in production

#### Super Stretch
- [ ] Hooking up a logging tool like Sentry

**Comment by nickcannariato** [comment]
Alright, I'm going to call it for the night. I got a _ton_ done, but there's still a bunch to do. 

Remaining tasks are below, emoji is colored by severity of the need for a fix

## Still Todo
- [ ] ( 🔴) Normalize the notifications, messages, and team_members tables  
- [ ] ( 🔴) Set up transactional DB calls in `team_member` controller to avoid the Route From Hell™️  
- [ ] ( 💛) Rename the `relational_table` and build a dedicated model for it
- [ ] ( 💛) Verify that all refactored models and controllers outside of the specific ones listed above are functional
- [ ] ( 💚) Write all of the tests
- [ ] ( 💚) Write all of the docs using JSDoc 

/cc @GannonDetroit @ajb85 @DaftBeowulf @TomHessburg

**Comment by nickcannariato** [comment]
With our deepest regards to v1 of Training Bot, the v2 refactor is now ready for review and merging. 🙇

**Comment by sabrinagear** [comment]
Dang you guys, way to #crushit 🔥 @nickcannariato

**Pull request merged**
